# Generated by Django 2.0.3 on 2018-03-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('organizacion', models.CharField(max_length=50)),
                ('cowner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urln', models.CharField(max_length=100)),
                ('red', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'Instagram'), ('YT', 'Youtbe'), ('OT', 'Otros')], max_length=2)),
                ('sowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('C', 'Celular'), ('P', 'Particular'), ('L', 'Laboral'), ('F', 'Principal'), ('O', 'Otros')], max_length=1)),
                ('towner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Contacto')),
            ],
        ),
    ]
