# Generated by Django 2.0.3 on 2018-03-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20180309_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='cowner',
            new_name='owner',
        ),
    ]
